### ISSUE TITLE
Relax rubygems version requirement

### ISSUE THREAD

**Issue by Jell** [AsteriskLabs/devise_google_authenticator#16]
This commit: https://github.com/AsteriskLabs/devise_google_authenticator/commit/8fb1fc509a7c06ce180c0f35f1ab399539dc1ef9

Changed the required version of rubygems from '>= 1.3.6' to '>= 2.1.0', any particular reason for this?

Could it be relaxed back to 1.3.6?

**Comment by xntrik** [comment]
Since commenting this out I haven't had problems. Closing out.
