### ISSUE TITLE
Supporting Mongoid and Yubikey OTPs

### ISSUE THREAD

**Issue by eimermusic** [AsteriskLabs/devise_google_authenticator#5]
Hi,
I was looking to extract some second factor auth stuff into a gem and found this to be a nice start. My requirements go a bit further in that I also need to support Yubikey and Mongoid.

I have a fork 
https://github.com/eimermusic/devise_google_authenticator

Where I have:
• implemented support for Mongoid (3) (tests don't run Mongoid backend)
• Possibly broken AR support (tests still pass)
• Added Yubikey OTP support.
• Users can have Google (OATH TOTP) and Yubikey active at the same time and login using either one.
• Not aliasing create in sessions controller (using a before filter instead).
• Various other refactorings and changes.
• No new tests (yet) for my added features.

Because I have taken my fork 2 steps sideways I am not at all sure if any of it would be suitable to merge back. Let me know if you would like me to create some PRs for any of the changes.

**Comment by xntrik** [comment]
I'm going to close this issue, but track multi provider support in Issue #17
