### ISSUE TITLE
Use with Active Admin

### ISSUE THREAD

**Issue by toreym** [AsteriskLabs/devise_google_authenticator#7]
I'm getting a route not found error when using Active Admin. I was able to get it to work by changing this line. But not sure the best way to fix it.

```
# respond_with resource, :location => { :controller => 'checkga', :action => 'show', :id => tmpid}
redirect_to "/admin/checkga?id=#{tmpid}"
```

**Comment by DeviDandu** [comment]
facing the same issue not working with rails admin

**Comment by imam-scs** [comment]
Hi , I have installed gem 'devise_google_authenticator' in rails 5.2.1 but i got error i.e,Gem Load Error is: undefined method `to_prepare' for ActionDispatch::Callbacks:Class
Did you mean?  to_param , please give me suggestion
